name = "min_ada"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["JS Demers"]
maintainers = ["JS Demers <jdeme051@uottawa.ca>"]
maintainers-logins = ["JSIT-20"]

executables = ["min_ada"]

[[depends-on]]
beta_types = "1.0.0"